from django.conf.urls import url, patterns, handler404
import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^edit_profile/$',views.edit_profile,name='edit_profile'),
    url(r'^about/$',views.about,name='about'),
    url(r'^viewProfile/(?P<userId>[0-9]+)/', views.viewProfile, name="view_profile"),
    url(r'^run/new/', views.uploadRun, name="new_run"),
    url(r'^run/(?P<runid>[0-9]+)/', views.viewRun, name="view_run"),
    url(r'^task/manage/', views.manageTask, name="manage_task"),
    url(r'^task/new/', views.uploadTask, name="new_task"),
    url(r'^task/(?P<taskid>[0-9]+)/delete', views.deleteTask, name="delete_task"),
    url(r'^task/(?P<taskid>[0-9]+)/edit', views.editTask, name="edit_task"),
    url(r'^task/(?P<taskid>[0-9]+)/', views.viewTask, name="view_task"),
    url(r'^track/new/', views.uploadTrack, name="new_track"),
    url(r'^track/manage/', views.manageTrack, name="manage_track"),
    url(r'^track/(?P<trackid>[0-9]+)/delete', views.deleteTrack, name="delete_track"),
    url(r'^track/(?P<trackid>[0-9]+)/edit', views.editTrack, name="edit_track"),
    url(r'^track/(?P<trackid>[0-9]+)/', views.viewTrack, name="view_track"),
    url(r'^genre/new/', views.uploadGenre, name="new_genre"),
    url(r'^genre/manage/', views.manageGenre, name="manage_genre"),
    url(r'^genre/(?P<genreid>[0-9]+)/delete', views.deleteGenre, name="delete_genre"),
    url(r'^genre/(?P<genreid>[0-9]+)/edit', views.editGenre, name="edit_genre"),
    url(r'^browse/task/(?P<taskid>[0-9]+)/$', views.browseComplete, name='browseComplete'),
    url(r'^browse/(?P<trackid>[0-9]+)/$', views.browseTrack, name='browseTrack'),
    url(r'^browse/$', views.browse, name='browse'),
    url(r'^search/results', views.search, name="searchRes"),
    url(r'^search/$', views.searchForm, name='search'),
    url(r'^getOrgsJson/$', views.getOrgsJson),
    url(r'^getUsrnameJson/$', views.getUsrnameJson),
    url(r'^getNameJson/$', views.getNameJson),
    url(r'^getRunNameJson/$', views.getRunNameJson),
    url(r'^getTrackInfoJson/$', views.getTrackInfoJson),
    url(r'^getTaskInfoJson/$', views.getTaskInfoJson),
    url(r'^getTasksJson/$', views.getTasksJson),
    )